###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=elasticsearch
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
      ports:
        - "3309:3306"

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "87:80"
      links:
        - mysql
      environment:
        - PMA_HOST=mysql

    php-fpm:
      image: hitalos/laravel
      working_dir: /var/www
      links:
          - mysql
      volumes:
          - ./:/var/www
          - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      ports:
       - "86:80"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:edge-4.8
      working_dir: /application
      ports:
       - "8099:80"
      links:
       - mysql
      environment:
        - PMA_HOST=mysql
    elasticsearch:
      image: elasticsearch:7.5.2
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=192.168.48.1:9300
        - cluster.initial_master_nodes=192.168.48.1